using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class UIManager : MonoBehaviour
{
    public static UIManager instance;
    public Text sunNumText;
    // Start is called before the first frame update
    void Start()
    {
        instance = this;   
    }

    // Update is called once per frame
    void Update()
    {
        
    }
    public void InitUI()
    {
        sunNumText.text = GameManager.instance.SunNum.ToString();
    }
    public void UpdateUI()
    {
        sunNumText.text = GameManager.instance.SunNum.ToString();
    }
}
